language: ruby
rvm:
- 2.1.1
bundler_args: "--without development production autotest"
before_install:
- gem update --system
- travis_retry gem install bundler --pre
before_script:
- cp -f config/database.travis.yml config/database.yml
- cp -f .env.example .env
- bin/rake db:create db:schema:load RAILS_ENV=test
env:
  global:
    secure: iZRMHtUq5szn8jlUurVOb1S07JDW9hLFKaynkhYHZ0vShdRXJW9gSApzio/U/fKWYDp0xO8eBu9cBdtGqq7p1qQBB7+WB0ClMVL/faZMssY/erZfVle12vclPazQis37LEXNaalvEa7cI2TX3/3pC5jIfFxfr0IFWYlhpIvzINc=
deploy:
  provider: heroku
  api_key:
    secure: GXRnr0/ZeEjLS60bwkWUeEhRvpjcivSBSH8RduUgxepy9+AaCiCE3WyL0HLeoTn1rTAe0rhgB5oCYKUhhgiB0mRm7oLOVNUfclOnf8VBAxxhpuMGUaG0GLN3LcMveYKvE/buuwgn7yi73xkD2CZUJnnn4dWIJ+/45VY2yOg/WbE=
  app: uglst
  on:
    repo: ugtastic/uglst
