default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: 5432
  username: uglst

development:
  <<: *default
  database: uglst_development

test:
  <<: *default
  database: uglst_test
