development:
  database: uglst_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: 5432
  username: uglst

test:
  adapter: postgresql
  database: uglst_test
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: 5432
  username: uglst
