# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b778326473328cdbb6aae2fe6955e50787a8febc2bb4ee2c430deec8d06b82ef29196f814fd7bdb07e33f5e0b3f776191a35c8e52ded4852fd2297e1fa68db2

test:
  secret_key_base: 702cac70de916cb5087140aeba00a94a7d82e19972e28b6e3f3f9286bff2bbc6f844f6f7fcb7fe34ca5c35cfcc93340dbef68dafdbd367cb9d6133b708c1cdea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
